/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as GiveRouteImport } from './routes/give'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BibleStudiesRouteImport } from './routes/bible-studies'
import { Route as ArtworksRouteImport } from './routes/artworks'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SermonsIndexRouteImport } from './routes/sermons.index'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BibleStudiesIndexRouteImport } from './routes/bible-studies.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SermonsSlugRouteImport } from './routes/sermons.$slug'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BibleStudiesSlugRouteImport } from './routes/bible-studies.$slug'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSermonsRouteImport } from './routes/admin.sermons'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminNotAuthorizedRouteImport } from './routes/admin.not-authorized'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBibleStudiesRouteImport } from './routes/admin.bible-studies'
import { Route as AdminArtworksRouteImport } from './routes/admin.artworks'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as AdminSectionRouteImport } from './routes/admin.$section'
import { Route as AdminSermonsIndexRouteImport } from './routes/admin.sermons.index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin.events.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as AdminBibleStudiesIndexRouteImport } from './routes/admin.bible-studies.index'
import { Route as AdminArtworksIndexRouteImport } from './routes/admin.artworks.index'
import { Route as AdminArticlesIndexRouteImport } from './routes/admin.articles.index'
import { Route as AdminSermonsNewRouteImport } from './routes/admin.sermons.new'
import { Route as AdminSermonsIdRouteImport } from './routes/admin.sermons.$id'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminEventsIdRouteImport } from './routes/admin.events.$id'
import { Route as AdminBlogNewRouteImport } from './routes/admin.blog.new'
import { Route as AdminBlogIdRouteImport } from './routes/admin.blog.$id'
import { Route as AdminBibleStudiesNewRouteImport } from './routes/admin.bible-studies.new'
import { Route as AdminBibleStudiesIdRouteImport } from './routes/admin.bible-studies.$id'
import { Route as AdminArtworksNewRouteImport } from './routes/admin.artworks.new'
import { Route as AdminArtworksIdRouteImport } from './routes/admin.artworks.$id'
import { Route as AdminArticlesNewRouteImport } from './routes/admin.articles.new'
import { Route as AdminArticlesIdRouteImport } from './routes/admin.articles.$id'

const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleStudiesRoute = BibleStudiesRouteImport.update({
  id: '/bible-studies',
  path: '/bible-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksRoute = ArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsIndexRoute = SermonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SermonsRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BibleStudiesIndexRoute = BibleStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibleStudiesRoute,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SermonsSlugRoute = SermonsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SermonsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BibleStudiesSlugRoute = BibleStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BibleStudiesRoute,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticlesRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSermonsRoute = AdminSermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotAuthorizedRoute = AdminNotAuthorizedRouteImport.update({
  id: '/not-authorized',
  path: '/not-authorized',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBibleStudiesRoute = AdminBibleStudiesRouteImport.update({
  id: '/bible-studies',
  path: '/bible-studies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtworksRoute = AdminArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSermonsIndexRoute = AdminSermonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSermonsRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBibleStudiesIndexRoute = AdminBibleStudiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBibleStudiesRoute,
} as any)
const AdminArtworksIndexRoute = AdminArtworksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminArtworksRoute,
} as any)
const AdminArticlesIndexRoute = AdminArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const AdminSermonsNewRoute = AdminSermonsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminSermonsRoute,
} as any)
const AdminSermonsIdRoute = AdminSermonsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSermonsRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminEventsIdRoute = AdminEventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminBlogNewRoute = AdminBlogNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBlogIdRoute = AdminBlogIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBlogRoute,
} as any)
const AdminBibleStudiesNewRoute = AdminBibleStudiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminBibleStudiesRoute,
} as any)
const AdminBibleStudiesIdRoute = AdminBibleStudiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminBibleStudiesRoute,
} as any)
const AdminArtworksNewRoute = AdminArtworksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArtworksRoute,
} as any)
const AdminArtworksIdRoute = AdminArtworksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminArtworksRoute,
} as any)
const AdminArticlesNewRoute = AdminArticlesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminArticlesRoute,
} as any)
const AdminArticlesIdRoute = AdminArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminArticlesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/artworks': typeof ArtworksRoute
  '/bible-studies': typeof BibleStudiesRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/give': typeof GiveRoute
  '/newsletter': typeof NewsletterRoute
  '/sermons': typeof SermonsRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/artworks': typeof AdminArtworksRouteWithChildren
  '/admin/bible-studies': typeof AdminBibleStudiesRouteWithChildren
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/not-authorized': typeof AdminNotAuthorizedRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/sermons': typeof AdminSermonsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/bible-studies/$slug': typeof BibleStudiesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/sermons/$slug': typeof SermonsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/bible-studies/': typeof BibleStudiesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/sermons/': typeof SermonsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/artworks/$id': typeof AdminArtworksIdRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/admin/bible-studies/$id': typeof AdminBibleStudiesIdRoute
  '/admin/bible-studies/new': typeof AdminBibleStudiesNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/sermons/$id': typeof AdminSermonsIdRoute
  '/admin/sermons/new': typeof AdminSermonsNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/artworks/': typeof AdminArtworksIndexRoute
  '/admin/bible-studies/': typeof AdminBibleStudiesIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/sermons/': typeof AdminSermonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/artworks': typeof ArtworksRoute
  '/contact': typeof ContactRoute
  '/give': typeof GiveRoute
  '/newsletter': typeof NewsletterRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/not-authorized': typeof AdminNotAuthorizedRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/bible-studies/$slug': typeof BibleStudiesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/sermons/$slug': typeof SermonsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/articles': typeof ArticlesIndexRoute
  '/bible-studies': typeof BibleStudiesIndexRoute
  '/blog': typeof BlogIndexRoute
  '/events': typeof EventsIndexRoute
  '/sermons': typeof SermonsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/artworks/$id': typeof AdminArtworksIdRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/admin/bible-studies/$id': typeof AdminBibleStudiesIdRoute
  '/admin/bible-studies/new': typeof AdminBibleStudiesNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/sermons/$id': typeof AdminSermonsIdRoute
  '/admin/sermons/new': typeof AdminSermonsNewRoute
  '/admin/articles': typeof AdminArticlesIndexRoute
  '/admin/artworks': typeof AdminArtworksIndexRoute
  '/admin/bible-studies': typeof AdminBibleStudiesIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/admin/sermons': typeof AdminSermonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/articles': typeof ArticlesRouteWithChildren
  '/artworks': typeof ArtworksRoute
  '/bible-studies': typeof BibleStudiesRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/give': typeof GiveRoute
  '/newsletter': typeof NewsletterRoute
  '/sermons': typeof SermonsRouteWithChildren
  '/admin/$section': typeof AdminSectionRoute
  '/admin/articles': typeof AdminArticlesRouteWithChildren
  '/admin/artworks': typeof AdminArtworksRouteWithChildren
  '/admin/bible-studies': typeof AdminBibleStudiesRouteWithChildren
  '/admin/blog': typeof AdminBlogRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/not-authorized': typeof AdminNotAuthorizedRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/sermons': typeof AdminSermonsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/bible-studies/$slug': typeof BibleStudiesSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/sermons/$slug': typeof SermonsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/articles/': typeof ArticlesIndexRoute
  '/bible-studies/': typeof BibleStudiesIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/events/': typeof EventsIndexRoute
  '/sermons/': typeof SermonsIndexRoute
  '/admin/articles/$id': typeof AdminArticlesIdRoute
  '/admin/articles/new': typeof AdminArticlesNewRoute
  '/admin/artworks/$id': typeof AdminArtworksIdRoute
  '/admin/artworks/new': typeof AdminArtworksNewRoute
  '/admin/bible-studies/$id': typeof AdminBibleStudiesIdRoute
  '/admin/bible-studies/new': typeof AdminBibleStudiesNewRoute
  '/admin/blog/$id': typeof AdminBlogIdRoute
  '/admin/blog/new': typeof AdminBlogNewRoute
  '/admin/events/$id': typeof AdminEventsIdRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/sermons/$id': typeof AdminSermonsIdRoute
  '/admin/sermons/new': typeof AdminSermonsNewRoute
  '/admin/articles/': typeof AdminArticlesIndexRoute
  '/admin/artworks/': typeof AdminArtworksIndexRoute
  '/admin/bible-studies/': typeof AdminBibleStudiesIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/admin/sermons/': typeof AdminSermonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/artworks'
    | '/bible-studies'
    | '/blog'
    | '/contact'
    | '/events'
    | '/give'
    | '/newsletter'
    | '/sermons'
    | '/admin/$section'
    | '/admin/articles'
    | '/admin/artworks'
    | '/admin/bible-studies'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/not-authorized'
    | '/admin/pages'
    | '/admin/review'
    | '/admin/sermons'
    | '/admin/settings'
    | '/admin/team'
    | '/articles/$slug'
    | '/bible-studies/$slug'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/sermons/$slug'
    | '/admin/'
    | '/articles/'
    | '/bible-studies/'
    | '/blog/'
    | '/events/'
    | '/sermons/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/artworks/$id'
    | '/admin/artworks/new'
    | '/admin/bible-studies/$id'
    | '/admin/bible-studies/new'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/sermons/$id'
    | '/admin/sermons/new'
    | '/admin/articles/'
    | '/admin/artworks/'
    | '/admin/bible-studies/'
    | '/admin/blog/'
    | '/admin/events/'
    | '/admin/sermons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/artworks'
    | '/contact'
    | '/give'
    | '/newsletter'
    | '/admin/$section'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/media'
    | '/admin/not-authorized'
    | '/admin/pages'
    | '/admin/review'
    | '/admin/settings'
    | '/admin/team'
    | '/articles/$slug'
    | '/bible-studies/$slug'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/sermons/$slug'
    | '/admin'
    | '/articles'
    | '/bible-studies'
    | '/blog'
    | '/events'
    | '/sermons'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/artworks/$id'
    | '/admin/artworks/new'
    | '/admin/bible-studies/$id'
    | '/admin/bible-studies/new'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/sermons/$id'
    | '/admin/sermons/new'
    | '/admin/articles'
    | '/admin/artworks'
    | '/admin/bible-studies'
    | '/admin/blog'
    | '/admin/events'
    | '/admin/sermons'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/articles'
    | '/artworks'
    | '/bible-studies'
    | '/blog'
    | '/contact'
    | '/events'
    | '/give'
    | '/newsletter'
    | '/sermons'
    | '/admin/$section'
    | '/admin/articles'
    | '/admin/artworks'
    | '/admin/bible-studies'
    | '/admin/blog'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/media'
    | '/admin/not-authorized'
    | '/admin/pages'
    | '/admin/review'
    | '/admin/sermons'
    | '/admin/settings'
    | '/admin/team'
    | '/articles/$slug'
    | '/bible-studies/$slug'
    | '/blog/$slug'
    | '/events/$eventId'
    | '/sermons/$slug'
    | '/admin/'
    | '/articles/'
    | '/bible-studies/'
    | '/blog/'
    | '/events/'
    | '/sermons/'
    | '/admin/articles/$id'
    | '/admin/articles/new'
    | '/admin/artworks/$id'
    | '/admin/artworks/new'
    | '/admin/bible-studies/$id'
    | '/admin/bible-studies/new'
    | '/admin/blog/$id'
    | '/admin/blog/new'
    | '/admin/events/$id'
    | '/admin/events/new'
    | '/admin/sermons/$id'
    | '/admin/sermons/new'
    | '/admin/articles/'
    | '/admin/artworks/'
    | '/admin/bible-studies/'
    | '/admin/blog/'
    | '/admin/events/'
    | '/admin/sermons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArticlesRoute: typeof ArticlesRouteWithChildren
  ArtworksRoute: typeof ArtworksRoute
  BibleStudiesRoute: typeof BibleStudiesRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GiveRoute: typeof GiveRoute
  NewsletterRoute: typeof NewsletterRoute
  SermonsRoute: typeof SermonsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible-studies': {
      id: '/bible-studies'
      path: '/bible-studies'
      fullPath: '/bible-studies'
      preLoaderRoute: typeof BibleStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks': {
      id: '/artworks'
      path: '/artworks'
      fullPath: '/artworks'
      preLoaderRoute: typeof ArtworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons/': {
      id: '/sermons/'
      path: '/'
      fullPath: '/sermons/'
      preLoaderRoute: typeof SermonsIndexRouteImport
      parentRoute: typeof SermonsRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bible-studies/': {
      id: '/bible-studies/'
      path: '/'
      fullPath: '/bible-studies/'
      preLoaderRoute: typeof BibleStudiesIndexRouteImport
      parentRoute: typeof BibleStudiesRoute
    }
    '/articles/': {
      id: '/articles/'
      path: '/'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/sermons/$slug': {
      id: '/sermons/$slug'
      path: '/$slug'
      fullPath: '/sermons/$slug'
      preLoaderRoute: typeof SermonsSlugRouteImport
      parentRoute: typeof SermonsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bible-studies/$slug': {
      id: '/bible-studies/$slug'
      path: '/$slug'
      fullPath: '/bible-studies/$slug'
      preLoaderRoute: typeof BibleStudiesSlugRouteImport
      parentRoute: typeof BibleStudiesRoute
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sermons': {
      id: '/admin/sermons'
      path: '/sermons'
      fullPath: '/admin/sermons'
      preLoaderRoute: typeof AdminSermonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/not-authorized': {
      id: '/admin/not-authorized'
      path: '/not-authorized'
      fullPath: '/admin/not-authorized'
      preLoaderRoute: typeof AdminNotAuthorizedRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bible-studies': {
      id: '/admin/bible-studies'
      path: '/bible-studies'
      fullPath: '/admin/bible-studies'
      preLoaderRoute: typeof AdminBibleStudiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artworks': {
      id: '/admin/artworks'
      path: '/artworks'
      fullPath: '/admin/artworks'
      preLoaderRoute: typeof AdminArtworksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sermons/': {
      id: '/admin/sermons/'
      path: '/'
      fullPath: '/admin/sermons/'
      preLoaderRoute: typeof AdminSermonsIndexRouteImport
      parentRoute: typeof AdminSermonsRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/bible-studies/': {
      id: '/admin/bible-studies/'
      path: '/'
      fullPath: '/admin/bible-studies/'
      preLoaderRoute: typeof AdminBibleStudiesIndexRouteImport
      parentRoute: typeof AdminBibleStudiesRoute
    }
    '/admin/artworks/': {
      id: '/admin/artworks/'
      path: '/'
      fullPath: '/admin/artworks/'
      preLoaderRoute: typeof AdminArtworksIndexRouteImport
      parentRoute: typeof AdminArtworksRoute
    }
    '/admin/articles/': {
      id: '/admin/articles/'
      path: '/'
      fullPath: '/admin/articles/'
      preLoaderRoute: typeof AdminArticlesIndexRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/admin/sermons/new': {
      id: '/admin/sermons/new'
      path: '/new'
      fullPath: '/admin/sermons/new'
      preLoaderRoute: typeof AdminSermonsNewRouteImport
      parentRoute: typeof AdminSermonsRoute
    }
    '/admin/sermons/$id': {
      id: '/admin/sermons/$id'
      path: '/$id'
      fullPath: '/admin/sermons/$id'
      preLoaderRoute: typeof AdminSermonsIdRouteImport
      parentRoute: typeof AdminSermonsRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/events/$id': {
      id: '/admin/events/$id'
      path: '/$id'
      fullPath: '/admin/events/$id'
      preLoaderRoute: typeof AdminEventsIdRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/blog/new': {
      id: '/admin/blog/new'
      path: '/new'
      fullPath: '/admin/blog/new'
      preLoaderRoute: typeof AdminBlogNewRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/blog/$id': {
      id: '/admin/blog/$id'
      path: '/$id'
      fullPath: '/admin/blog/$id'
      preLoaderRoute: typeof AdminBlogIdRouteImport
      parentRoute: typeof AdminBlogRoute
    }
    '/admin/bible-studies/new': {
      id: '/admin/bible-studies/new'
      path: '/new'
      fullPath: '/admin/bible-studies/new'
      preLoaderRoute: typeof AdminBibleStudiesNewRouteImport
      parentRoute: typeof AdminBibleStudiesRoute
    }
    '/admin/bible-studies/$id': {
      id: '/admin/bible-studies/$id'
      path: '/$id'
      fullPath: '/admin/bible-studies/$id'
      preLoaderRoute: typeof AdminBibleStudiesIdRouteImport
      parentRoute: typeof AdminBibleStudiesRoute
    }
    '/admin/artworks/new': {
      id: '/admin/artworks/new'
      path: '/new'
      fullPath: '/admin/artworks/new'
      preLoaderRoute: typeof AdminArtworksNewRouteImport
      parentRoute: typeof AdminArtworksRoute
    }
    '/admin/artworks/$id': {
      id: '/admin/artworks/$id'
      path: '/$id'
      fullPath: '/admin/artworks/$id'
      preLoaderRoute: typeof AdminArtworksIdRouteImport
      parentRoute: typeof AdminArtworksRoute
    }
    '/admin/articles/new': {
      id: '/admin/articles/new'
      path: '/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminArticlesNewRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
    '/admin/articles/$id': {
      id: '/admin/articles/$id'
      path: '/$id'
      fullPath: '/admin/articles/$id'
      preLoaderRoute: typeof AdminArticlesIdRouteImport
      parentRoute: typeof AdminArticlesRoute
    }
  }
}

interface AdminArticlesRouteChildren {
  AdminArticlesIdRoute: typeof AdminArticlesIdRoute
  AdminArticlesNewRoute: typeof AdminArticlesNewRoute
  AdminArticlesIndexRoute: typeof AdminArticlesIndexRoute
}

const AdminArticlesRouteChildren: AdminArticlesRouteChildren = {
  AdminArticlesIdRoute: AdminArticlesIdRoute,
  AdminArticlesNewRoute: AdminArticlesNewRoute,
  AdminArticlesIndexRoute: AdminArticlesIndexRoute,
}

const AdminArticlesRouteWithChildren = AdminArticlesRoute._addFileChildren(
  AdminArticlesRouteChildren,
)

interface AdminArtworksRouteChildren {
  AdminArtworksIdRoute: typeof AdminArtworksIdRoute
  AdminArtworksNewRoute: typeof AdminArtworksNewRoute
  AdminArtworksIndexRoute: typeof AdminArtworksIndexRoute
}

const AdminArtworksRouteChildren: AdminArtworksRouteChildren = {
  AdminArtworksIdRoute: AdminArtworksIdRoute,
  AdminArtworksNewRoute: AdminArtworksNewRoute,
  AdminArtworksIndexRoute: AdminArtworksIndexRoute,
}

const AdminArtworksRouteWithChildren = AdminArtworksRoute._addFileChildren(
  AdminArtworksRouteChildren,
)

interface AdminBibleStudiesRouteChildren {
  AdminBibleStudiesIdRoute: typeof AdminBibleStudiesIdRoute
  AdminBibleStudiesNewRoute: typeof AdminBibleStudiesNewRoute
  AdminBibleStudiesIndexRoute: typeof AdminBibleStudiesIndexRoute
}

const AdminBibleStudiesRouteChildren: AdminBibleStudiesRouteChildren = {
  AdminBibleStudiesIdRoute: AdminBibleStudiesIdRoute,
  AdminBibleStudiesNewRoute: AdminBibleStudiesNewRoute,
  AdminBibleStudiesIndexRoute: AdminBibleStudiesIndexRoute,
}

const AdminBibleStudiesRouteWithChildren =
  AdminBibleStudiesRoute._addFileChildren(AdminBibleStudiesRouteChildren)

interface AdminBlogRouteChildren {
  AdminBlogIdRoute: typeof AdminBlogIdRoute
  AdminBlogNewRoute: typeof AdminBlogNewRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
}

const AdminBlogRouteChildren: AdminBlogRouteChildren = {
  AdminBlogIdRoute: AdminBlogIdRoute,
  AdminBlogNewRoute: AdminBlogNewRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
}

const AdminBlogRouteWithChildren = AdminBlogRoute._addFileChildren(
  AdminBlogRouteChildren,
)

interface AdminEventsRouteChildren {
  AdminEventsIdRoute: typeof AdminEventsIdRoute
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsIdRoute: AdminEventsIdRoute,
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminSermonsRouteChildren {
  AdminSermonsIdRoute: typeof AdminSermonsIdRoute
  AdminSermonsNewRoute: typeof AdminSermonsNewRoute
  AdminSermonsIndexRoute: typeof AdminSermonsIndexRoute
}

const AdminSermonsRouteChildren: AdminSermonsRouteChildren = {
  AdminSermonsIdRoute: AdminSermonsIdRoute,
  AdminSermonsNewRoute: AdminSermonsNewRoute,
  AdminSermonsIndexRoute: AdminSermonsIndexRoute,
}

const AdminSermonsRouteWithChildren = AdminSermonsRoute._addFileChildren(
  AdminSermonsRouteChildren,
)

interface AdminRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminArticlesRoute: typeof AdminArticlesRouteWithChildren
  AdminArtworksRoute: typeof AdminArtworksRouteWithChildren
  AdminBibleStudiesRoute: typeof AdminBibleStudiesRouteWithChildren
  AdminBlogRoute: typeof AdminBlogRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNotAuthorizedRoute: typeof AdminNotAuthorizedRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminSermonsRoute: typeof AdminSermonsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminArticlesRoute: AdminArticlesRouteWithChildren,
  AdminArtworksRoute: AdminArtworksRouteWithChildren,
  AdminBibleStudiesRoute: AdminBibleStudiesRouteWithChildren,
  AdminBlogRoute: AdminBlogRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNotAuthorizedRoute: AdminNotAuthorizedRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminSermonsRoute: AdminSermonsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticlesRouteChildren {
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface BibleStudiesRouteChildren {
  BibleStudiesSlugRoute: typeof BibleStudiesSlugRoute
  BibleStudiesIndexRoute: typeof BibleStudiesIndexRoute
}

const BibleStudiesRouteChildren: BibleStudiesRouteChildren = {
  BibleStudiesSlugRoute: BibleStudiesSlugRoute,
  BibleStudiesIndexRoute: BibleStudiesIndexRoute,
}

const BibleStudiesRouteWithChildren = BibleStudiesRoute._addFileChildren(
  BibleStudiesRouteChildren,
)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface SermonsRouteChildren {
  SermonsSlugRoute: typeof SermonsSlugRoute
  SermonsIndexRoute: typeof SermonsIndexRoute
}

const SermonsRouteChildren: SermonsRouteChildren = {
  SermonsSlugRoute: SermonsSlugRoute,
  SermonsIndexRoute: SermonsIndexRoute,
}

const SermonsRouteWithChildren =
  SermonsRoute._addFileChildren(SermonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ArticlesRoute: ArticlesRouteWithChildren,
  ArtworksRoute: ArtworksRoute,
  BibleStudiesRoute: BibleStudiesRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GiveRoute: GiveRoute,
  NewsletterRoute: NewsletterRoute,
  SermonsRoute: SermonsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
